export const mockData = [
  {
    id: 1,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 2,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 3,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 4,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 5,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 6,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 7,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 8,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 9,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 10,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 11,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 12,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 13,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 14,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 15,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 16,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 17,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 18,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 19,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 20,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 21,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 22,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 23,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 24,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 25,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 26,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 27,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 28,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 29,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
  {
    id: 30,
    column1: "カラム1",
    column2: "カラム2",
    column3: "カラム3",
    column4: "カラム4",
    column5: "カラム5",
    column6: "カラム6",
    column7: "カラム7",
  },
];
